version: '3.8'

services:
  traefik:
    image: "traefik:v2.10"
    container_name: "traefik_proxy"
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./letsencrypt:/letsencrypt"
      - "./traefik.yml:/etc/traefik/traefik.yml"
    labels:
      - "traefik.http.routers.api.rule=Host(`superearner.online`)"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls.certresolver=myresolver"
    command:
      - "--certificatesresolvers.myresolver.acme.email=cloudspeed98@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"

  fastapi:
    image: ec2-user-fastapi
    container_name: fastapi_service
    restart: always
    expose:
      - "8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi.rule=Host(`superearner.online`)"
      - "traefik.http.routers.fastapi.entrypoints=websecure"
      - "traefik.http.routers.fastapi.tls.certresolver=myresolver"
      - "traefik.http.services.fastapi.loadbalancer.server.port=8080"  # Correct port

